# Generated by Django 5.1 on 2025-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_color', models.CharField(default='2E86AB', max_length=6)),
                ('special_dark_color', models.CharField(default='065A82', max_length=6)),
                ('background', models.CharField(default='FFFFFF', max_length=6)),
                ('background_gray', models.CharField(default='F3F3F3', max_length=6)),
                ('background_dark', models.CharField(default='2d2d2d', max_length=6)),
                ('link', models.CharField(default='007BFF', max_length=6)),
                ('link_hover', models.CharField(default='0056B3', max_length=6)),
                ('text_color', models.CharField(default='282828', max_length=6)),
                ('text_color_hover', models.CharField(default='232323', max_length=6)),
                ('text_color_light', models.CharField(default='ffffff', max_length=6)),
                ('text_color_light_hover', models.CharField(default='F3EFF5', max_length=6)),
            ],
            options={
                'verbose_name': 'Site color palette',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Site Name', max_length=255)),
                ('description', models.TextField(default='Site Description', max_length=750)),
                ('description_short', models.TextField(default='Site Short Description', max_length=128)),
                ('keywords', models.TextField(default='keyword1, keyword2, keyword3, keyword4', max_length=750)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('fa_icon', models.CharField(max_length=64)),
            ],
        ),
    ]
